# Generated by Django 5.0.14 on 2026-07-26 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("intent", "0001_initial"),
        ("kinds", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeclaredResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("tenant_id", models.UUIDField()),
                ("name", models.CharField(max_length=253)),
                ("scope", models.CharField(max_length=253)),
                ("provider_id", models.CharField(blank=True, max_length=253, null=True)),
                ("attributes", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="kinds.kind"),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="intent.intentrevision"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="declaredresource",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "kind", "scope", "name", "revision"),
                name="uq_declared_natural_key_per_revision",
            ),
        ),
    ]
