# Generated by Django 5.0.14 on 2026-07-26 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("kinds", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectorRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("tenant_id", models.UUIDField()),
                ("collector_name", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("partial", "Partial"),
                            ("failed", "Failed"),
                        ],
                        max_length=16,
                    ),
                ),
                ("resources_read", models.IntegerField(default=0)),
                ("resources_written", models.IntegerField(default=0)),
                ("errors", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="DiscoveredResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("tenant_id", models.UUIDField()),
                ("name", models.CharField(max_length=253)),
                ("scope", models.CharField(max_length=253)),
                ("provider_id", models.CharField(max_length=253)),
                ("attributes", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="kinds.kind"),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="discovery.collectorrun"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="discoveredresource",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "kind", "scope", "name"), name="uq_discovered_natural_key"
            ),
        ),
    ]
