# Generated by Django 5.0.14 on 2026-07-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discovery", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectorrun",
            name="has_gap",
            field=models.BooleanField(default=False),
        ),
    ]
