# Generated by Django 5.0.14 on 2026-07-26 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("discovery", "0001_initial"),
        ("graph", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Discrepancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("tenant_id", models.UUIDField()),
                (
                    "discrepancy_type",
                    models.CharField(
                        choices=[
                            ("field", "Field"),
                            ("declared_missing", "Declared Missing"),
                            ("discovered_undeclared", "Discovered Undeclared"),
                        ],
                        max_length=24,
                    ),
                ),
                ("kind_name", models.CharField(max_length=128)),
                ("scope", models.CharField(max_length=253)),
                ("name", models.CharField(max_length=253)),
                ("field_name", models.CharField(blank=True, max_length=128, null=True)),
                ("declared_value", models.JSONField(blank=True, null=True)),
                ("discovered_value", models.JSONField(blank=True, null=True)),
                (
                    "authoritative_plane",
                    models.CharField(
                        choices=[("declared", "Declared"), ("discovered", "Discovered")],
                        default="declared",
                        max_length=12,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("open", "Open"), ("resolved", "Resolved")],
                        default="open",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("tenant_id", models.UUIDField()),
                (
                    "strategy",
                    models.CharField(
                        choices=[
                            ("natural_key", "Natural Key"),
                            ("binding", "Binding"),
                            ("provider_tag", "Provider Tag"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "confidence",
                    models.CharField(
                        choices=[("high", "High"), ("medium", "Medium"), ("low", "Low")],
                        max_length=8,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("confirmed", "Confirmed"),
                            ("rejected", "Rejected"),
                        ],
                        default="proposed",
                        max_length=12,
                    ),
                ),
                ("confirmed_by", models.CharField(blank=True, max_length=128, null=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "declared_resource",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="graph.declaredresource"
                    ),
                ),
                (
                    "discovered_resource",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="discovery.discoveredresource",
                    ),
                ),
            ],
        ),
    ]
