# Generated by Django 5.0.14 on 2026-07-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IntentRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("tenant_id", models.UUIDField()),
                ("commit_sha", models.CharField(max_length=64)),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name="intentrevision",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "commit_sha"), name="uq_revision_tenant_commit"
            ),
        ),
        migrations.AddConstraint(
            model_name="intentrevision",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("tenant_id",),
                name="uq_one_active_revision_per_tenant",
            ),
        ),
    ]
