"""Generate web/src/enums.ts from datum/enums.py. Single source of truth."""

import os
from pathlib import Path

import django

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "datum.settings")
django.setup()

from django.db.models import TextChoices  # noqa: E402

from datum import enums  # noqa: E402

lines = ["// GENERATED by scripts/gen_ts_enums.py — do not edit.", ""]
for attr in dir(enums):
    obj = getattr(enums, attr)
    if isinstance(obj, type) and issubclass(obj, TextChoices) and obj is not TextChoices:
        lines.append(f"export enum {attr} {{")
        for member in obj:
            lines.append(f'  {member.name} = "{member.value}",')
        lines.append("}")
        lines.append("")

out = Path("web/src/enums.ts")
out.parent.mkdir(parents=True, exist_ok=True)
# newline="" suppresses platform translation: the generated file is byte-identical
# on Windows and Linux, so regenerating never produces a spurious diff.
out.write_text("\n".join(lines), encoding="utf-8", newline="")
print(f"wrote {out}")
