// GENERATED by scripts/gen_ts_enums.py — do not edit.

export enum CollectorRunStatus {
  SUCCESS = "success",
  PARTIAL = "partial",
  FAILED = "failed",
}

export enum Confidence {
  HIGH = "high",
  MEDIUM = "medium",
  LOW = "low",
}

export enum DiscrepancyState {
  OPEN = "open",
  RESOLVED = "resolved",
}

export enum DiscrepancyType {
  FIELD = "field",
  DECLARED_MISSING = "declared_missing",
  DISCOVERED_UNDECLARED = "discovered_undeclared",
}

export enum MatchState {
  PROPOSED = "proposed",
  CONFIRMED = "confirmed",
  REJECTED = "rejected",
  INVALIDATED = "invalidated",
}

export enum MatchStrategy {
  NATURAL_KEY = "natural_key",
  BINDING = "binding",
  PROVIDER_TAG = "provider_tag",
}

export enum Plane {
  DECLARED = "declared",
  DISCOVERED = "discovered",
}
